ed-donner/llm_engineering

week1/day1.ipynb
Added updated Website class to parse webpages which is designed using JavaScript heavily, at the end of week1 day1 notebook and tested the open AI summarization output using openai, cnn, edwarddonner webpages.
=> Added updated Website class to parse webpages which is designed using JavaScript 

week2/community-contributions/day2.ipynb
Added a new function to get results with Gemini
=> Stream_Gemini

week1/community-contributions/day1-article-pdf-reader.ipynb
Adding my contribution for the 1st day. Article PDF reader feature.
=> Adding contribution

week2/community-contributions/day3.upsell.ipynb
Hi Ed,
Hopefully that's fixed it now
Cheers Paul
=> Upsell '3 for 2' option added

week1/community-contributions/day1-webscraping-selenium-for-javascript.ipynb
I added new class `WebsiteCrawler` and keep intact original class. Also, create similar function `new_summary` passing with additional parameter chrome_path which is require for selenium. Please check it. Thank you for teaching us!
=> Day 1 selenium challenged completed

week4/day4.ipynb
Change function from stream_code_quen to stream_code_qwen
=> Correct typo in week4/day4.ipynb

week1/community-contributions/day2 EXERCISE.ipynb
=> Week-1 day-2 Exercise

week1/community-contributions/day-1-generate-cover-letter-from-cv.ipynb, week1/community-contributions/resume.txt
Summarise a CV (resume.txt) then generate a cover letter from this CV - user will be prompted to enter a job description and this will also be used when generating the cover letter.
=> Adding example that shows how to generate cover letter from cv

week1/community-contributions/week1 EXERCISE.ipynb
I have added my solution for the exercise.
I have little bit different solution for the ollama then learnt better solution from yours.
=> Week 1 Exercise

week2/day4.ipynb
A minor suggestion to make the code more readable
=> improve readability

week1/community-contributions/week1-collaborative-approach-two-llms.ipynb
First solution I design to get response from your favorite LLM and second is colloborative approach of two LLM added might be good specimen for the upcoming student to think about it even better and good approach to refine this approach I leave it from them
=> Two Nice Solution added; First, Select the best LLM, Second approach is collaborative.

week2/community-contributions/day4-handle-multiple-tool-call.ipynb
An alternate version of the week 2 day 4 code, which is able to handle multiple tool calls at once.
Example prompt to trigger 2 tool calls: "Could you tell me which plane ticket is cheaper, Berlin or Paris?"
=> Week 2 Day 4 - handle multiple tool calls

week2/community-contributions/day1-gpt-llama-gemini-together.ipynb
Added solution where 3 llms are talking to each other with different perspective.
=> LLMs 3 way solution including ollama

week4/day4.ipynb
Happy to help. I noticed that I identified a Macintosh as a Linux box. Copy-and-paste error and no Mac to test...
=> Correctly identify Mac as a Mac not Linux

week2/community-contributions/Gemini-api.ipynb, week2/community-contributions/day2-gemini.ipynb, week2/community-contributions/day3-gemini.ipynb
Hi, I have tried and added week2: day1, day2 and day3 codes using gemini api instead of using openai api.
while learning to learn something new I will try everything using Gemini api as a learning challenge, looking forward to contribute to learning-community.
=> Week 2 Gemini Codes

week5/community-contributions/day5 - generating answers with citations.ipynb
**Community contributions : Week 5**
Added a Notebook to week 5 community contributions which contains a sample showing how to generate answers with inline & end of the answer citations pointing to the original source document used to answer the question
=> Generating answers with source citations - Community contributions

week1/community-contributions/day1-generate-social-media-posts.ipynb
Generates social media posts for Twitter, Instagram and Facebook for a given event website.
**Example:**
For an event website like [this](https://www.eventbrite.ie/e/startup-mastery-leveraging-lean-startup-agile-and-design-thinking-tickets-920474252267), it generates the following social media posts:
=> Day1: Generate social media posts for 3 platforms for an event

week1/community-contributions/day-1-Stock-data-analysis.ipynb
This notebook uses Yahoo finances webpage to get data of stock price changes over a year's timeframe and uses open AI APIs to get trend analysis on this data from "gpt-4o-mini"
=> Day 1: Notebook to analyze trends in stock price change

week2/community-contributions/day5_llama3.1_tools_usecase.ipynb
notebook : week2/community-contributions/day5_llama3.1_tools_usecase.ipynb
description:
implemented llama3.10-instruct tools usecase.
=> feat(week2): llama3.1-instruct tools usecase

week4/community-contributions/week4-day5-code-commenter.ipynb
A code tool that automatically adds docstring / comments. Keeping it simple. Used LLM to generate docstrings and code comments. I checked with an LLM to give me the most effective system and user prompt.
=> My Attempt at Code Docstringer and Commenter

week1/community-contributions/day1_email_reviewer.ipynb
Hi Ed,
As part of this PR, I’m uploading the email review and generating subject lines for the email content. Additionally, this process helps identify the tone of the email as well.
=> email reviewer application

week1/community-contributions/day1-resume-analyzer-for-job-postings.ipynb
This tool is designed to analyze resumes against specific job postings, offering valuable insights such as:
- Identification of skill gaps
- Keyword matching between the CV and the job description
- Tailored recommendations for CV improvement
- An alignment score reflecting how well the CV fits the job
- Personalized feedback
- Job market trend insights
=> Week1-Day1 project: Created a resume analyzer for job postings

week1/community-contributions/day2-ollama-website-summarizer.ipynb
This script is a complete example of the day 1 program, which uses OpenAI API to summarize websites, altered to use techniques from the day 2 exercise to call Ollama models locally.
=> notebook for day2 exercise, summarize websites using ollama

week4/community-contributions/Code_Converter(Added_Java_Support)(Open_Ai_Only).ipynb
Added java support with open ai only
=> Added Java Support WEEK 4 DAY3

week2/community-contributions/day1-conversation-with-gemini.ipynb
This is a reworking of the initial chat exercise on week 2 day 1. The original uses GPT and Claude, whereas this one eschews Claude for Gemini.
I found that Claude has to be set up with billing before you can call the API, whereas Gemini does not.
Gemini also has a [nice chat function in its Python SDK](https://ai.google.dev/gemini-api/docs/text-generation?lang=python#chat) which we use here.
=> barry_northern: using Gemini SDK instead of Claude + use Gemini's chat function.

week1/community-contributions/day1-wiki-summary.ipynb
Hi Ed, submitting a PR for sharing a small exercise i did to summarize content from Wiki page.
=> Added Wikipage summary exercise to community-contributions

week1/community-contributions/day1_analyze_CV_Write_cover_letter.ipynb
1. This version will Analyze your CV against the job description and if the CV is compatible with the job then it will write a **cover letter**.  It will also give a short summary of how the CV is fit or not fit for the job.
2. The job description is fetched using a URL, so you need to paste the URL instead of the job description text.
3. If either the job URL or CV is just random text or fake, then it will not write a cover letter instead tells you to enter the correct information.
=> Added my day1 contribution to community-contributions

week3/community-contributions/ai-web-summarizer/.gitignore, week3/community-contributions/ai-web-summarizer/README.md, week3/community-contributions/ai-web-summarizer/main.py, week3/community-contributions/ai-web-summarizer/requirements.txt, week3/community-contributions/ai-web-summarizer/summarizer/fetcher.py, week3/community-contributions/ai-web-summarizer/summarizer/summarizer.py, week3/community-contributions/ai-web-summarizer/utils/config.py, week3/community-contributions/ai-web-summarizer/utils/logger.py
This project is a simple AI-powered web page summarizer that leverages OpenAI's GPT models and local inference with Ollama to generate concise summaries of given text. The goal is to create a "Reader's Digest of the Internet" by summarizing web content efficiently.
=> ai-web-summarizer

week1/community-contributions/day1_industrial_product_recommendaitons.ipynb
For my Day 1 project exercise, I have developed an AI assistant designed to help users identify the most suitable industrial products for their specific needs.  
The primary objective is to assist individuals who lack technical knowledge about industrial tools and hardware, enabling them to find the right products effortlessly.  
The AI assistant follows these steps to provide recommendations:  
1. **Understanding the User's Scenario**  
- It analyzes the situation described by the customer to comprehend their specific needs.  
2. **Identifying the Relevant Product Category**  
- Based on the scenario, it determines the appropriate category of industrial products that would best suit the use case.  
3. **Searching Industrywaala.com**  
- It searches …
=> Added my contributions to community-contributions

week1/community-contributions/Week1_Challenge_Career_Well_Being_Companion.ipynb
This project will gather feelings at the end of day from employee.
Based on employee feelings provided as input, model will analyze feelings and provide suggestions and acknowledge with feelings employtee is going thru.
Model even will ask employee "Do you want more detailed resposne to cope up with your feelings?".
If employee agrees, model even replies with online courses, tools, meetups and other ideas for the well being of the employee.
Immediate Impact: Professionals can quickly see value through insights or actionable suggestions.
=> Added Week1 challenge , LLM acts like well being companion of employee.

week1/community-contributions/day1-email-reviewer-in-Bahasa.ipynb, week1/community-contributions/day2-exercise.ipynb
Hi Ed, big appreciate for your class. I promise i will finish the 8 week course. 
Added notebooks for topic day1 and day2 in week1 in community-contributions
=> Add contributions for day1 and day2 in community-contributions

week1/community-contributions/day1_quiz_generator.ipynb
This pull request introduces an AI-Powered Quiz Generator, a simple yet effective tool that generates multiple-choice quizzes on any topic using OpenAI's chat.completions.create API. The tool is designed to help users quickly create quizzes for learning, teaching, or self-assessment.
=> QuizGenerator - CommunityContribution

week1/community-contributions/week1-coderesearcher.py
I added a python code that takes personalised input and return the explanation and possible code improvements
=> Create my contribution week1-coderesearcher.py

week1/community-contributions/day1-Groq API.ipynb, week1/community-contributions/day1-Groq-API.ipynb
=> DAY1 LLM Project with GROQ!

week1/community-contributions/day-1-ollama-app.ipynb, week2/community-contributions/day3-gradio-auth.ipynb
Hi Ed,
Thank you for creating such an excellent course! I’ve really enjoyed learning from it and appreciate the effort you’ve put into the material.
I’ve created two experimental projects using the code you provided in your Jupyter notebook. Although they are simple and silly implementations, I thought they might be worth sharing:
Tkinter-Based App for Ollama
This app enables users to interact with Ollama through a GUI instead of using the command terminal. However, I’m not entirely confident about how to make the Tkinter code look polished within a Jupyter notebook. Since the input boxes aren’t defined when the function is created, the code may appear broken at first glance.
Gradio Authentication Enhancement
I added two additional lines to your Gradio code to include authentication. I …
=> Tkinter and Gradio Code Projects (two very silly projects)

week1/community-contributions/0225_day2_exercise_by_LM.ipynb
Alongside the exercise for summarizing the URL with Ollama, I’ve created a slightly different method, display_summary, which also allows you to pass the LLM model as a parameter.
=> Added my contributions to community-contributions day 2 exercise

week4/day4.ipynb
Hi, Ed!
I'm Motoya, an engineer from Japan.
I'm really excited every day taking your course!
Thank you so much as always!
By the way, while going through the course, I ran into an error because a list declaration was missing.
I’ll be sending a pull request with the fix, so please take a look!
=> Fixed an issue where compiler_cmd was undefined.

week1/community-contributions/day2-webpage-summarizer-ollama-gemini.ipynb
Add ollama and gemini support to web page summarizer.
=> Add first commit to community contributions

week2/community-contributions/day2_message_interface_with_models.ipynb
In my example, a user can ask a question and get a response from the GPT, Claude, and Gemini. You don't need to select a model and re-type the question. It might be helpful to see all responses on one screen and pick the best one :-)
=> Jupyter notebook to ask a question and get a response from the GPT, Claude, and Gemini

week5/community-contributions/day4.5 - langchain faiss ollama.ipynb
This pull request introduces an experimental change where the OpenAI API is replaced with Ollama, along with the integration of the FAISS vector database. The goal of these changes is to provide a solution for users who lack access to paid LLMs, by leveraging the capabilities of Ollama to offer an alternative, cost-effective approach.
Key changes include:
* Replacing OpenAI API calls with Ollama for embedding and inference processes.
* Integrating FAISS for efficient vector-based searches, as demonstrated in course.
=> Create day4.5 - langchain faiss ollama.ipynb

week2/community-contributions/day1-debate-gemini-judges.ipynb
- Add my version of `day1` notebook to `communicate-contribution` folder. This contains a spirited debate between GPT and Claude on Chomsky's theory of language origins and finally an evaluation of the arguments by gemini.
=> Add my day1 file

week1/community-contributions/day2_exercise_cl.ipynb
=> day2_exercise_cl.ipynb

week2/community-contributions/day4-multipleTools.ipynb
using 2 tools for ticket and check weather.
=> example of using 2 tools at the same time, week2, day4

week4/community-contributions/day4_with_inference_provider.ipynb
Added the use of inference providers that was introduced recently by Hugging Face to convert the code. Improved the user prompt to include algorithmic efficiency and performance optimization.
=> added day4 exercise with inference provider

week2/community-contributions/day1_triple_conversation.ipynb
A redo of [PR #150](https://github.com/ed-donner/llm_engineering/pull/150) ... sorry for the oversight, @ed-donner
=> Add 3-way conversation to community contributions (take 2)

week2/community-contributions/day4_with_booking_and_multiple_tools_per_message.ipynb
- the multiple tool fix is slightly different to another contribution, using a functional approach.
- without the fix you get an error about the fact that all tool ids must follow in messages that request them.
- this occurs when, for example, you ask for prices for two cities.
- the booking function and prompts allow you to book at a different price if you ask explicitly.
- this can be fun if you start asking about the discount applied.
=> barry_northern: booking function and multiple tools calls

extras/community/prototype_signal.ipynb
Added a Jupyter notebook at extras/community/signals.
the purpose of it to provide long-term, mid-term and short-term signals based on realtime data that has been provided by [Coin API](https://www.coinapi.io/)
=> Added Signal by LLMs

week1/community-contributions/day5-ollama.ipynb
**day5.ipynb Ollama version for Ollama users to follow up easily with week1 day5 videos.**
=> Week1 Day5 Ollama Version

week1/community-contributions/Week1-Exercise-OllamaStream-Solution.ipynb
**Used Ollama and Added Streaming for Llama Models.**
=> Week1 Exercise Ollama Solution with Streaming

week2/community-contributions/Week2_day2_openRouter_gradio_brochure.ipynb, week2/community-contributions/day2-openrouterAi.ipynb
with openrouter.ai,  can access all LLM with openAi sdk,
And there are many free mode you can use include google, meta and deepseek, etc
=> Add week2 with openrouter.ai and day 2 brochure practice

week3/community-contributions/day4_OCR_model_exercise.ipynb
I saw a slim OCR model and wanted to give it a try.
It runs so quickly on the free-tier T4 GPU runtime! And the implementation was easy (with a little help from Gemini on how to install the latest transformer libraries).
This thing reads my handwriting ... mind blown.
=> notebook for simple OCR model (uploaded from Colab)

week1/community-contributions/day1_ppt_summariser.ipynb, week1/community-contributions/day1_wiki_summariser.ipynb
Added notebook for Day 1 Task to community-contributions
=> Added contribution 'PPT Summariser' to community-contributions

week1/community-contributions/day5 - brochure improved.ipynb, week1/community-contributions/week1 EXERCISE - TechTutor.ipynb
- Improvements day5 brochure
- Implemented TechTutor as week1 Exercise
=> Added day5 and week1 Exercises

week1/community-contributions/day1-selenium-for-javascript-sites.ipynb, week1/community-contributions/day1-selenium-lama-mac.ipynb
Faced some challenges while setting up selenium for the mac.
=> Mac lama selenium

week5/community-contributions/day3-gemini.ipynb, week5/community-contributions/day4-gemini.ipynb
I have tried doing day 3 and day 4 of week5 Rag pipeline using Google Gemini
=> gemini-codes-week5

week1/community-contributions/day-1-marketing_insights_scraper.py, week1/community-contributions/day1_marketing_insights_scraper_Selenium_OpenAI.py
This PR introduces a fully automated Python script to extract key marketing insights from multiple websites.
The script:
- Uses Selenium to scrape website content dynamically.
- Queries OpenAI to generate concise insights for 9 key aspects.
- Saves the extracted data into a well-structured Excel file.
- Formats output properly, preventing duplicated column headers.
- Supports batch processing of multiple websites at once.
=> Week1-Day1:  Automated Website Content Analysis Script for SEO & Marketing Insights

week2/community-contributions/week2_code_interpreter_tool.ipynb
Added an example in Week2 community-contributions:
python interpreter as a tool, with multi shot prompting.
=> contribute to week 2 examples with a tool: python interpreter

week1/community-contributions/Week_1-Day 2-Article_Title_Generator.ipynb, week1/community-contributions/Week_1-Day 5-Article_Title_Generator-V2.ipynb
Week1 Day 2 Challenge
Summarization use-case in which the user provides an article, which the LLM will analyze to suggest an SEO-optimized title.
=> Article Title Generator

week5/community-contributions/day 4 no_langchain/RAG_chat_no_LangChain.ipynb, week5/community-contributions/day 4 no_langchain/knowledge_collection/languages/alsacien.md, week5/community-contributions/day 4 no_langchain/knowledge_collection/languages/bourguignon.md, week5/community-contributions/day 4 no_langchain/knowledge_collection/languages/breton.md, week5/community-contributions/day 4 no_langchain/knowledge_collection/languages/gascon.md, week5/community-contributions/day 4 no_langchain/knowledge_collection/languages/languedocien.md, week5/community-contributions/day 4 no_langchain/knowledge_collection/languages/lorrain.md, week5/community-contributions/day 4 no_langchain/knowledge_collection/languages/normand.md, week5/community-contributions/day 4 no_langchain/knowledge_collection/languages/picard.md, week5/community-contributions/day 4 no_langchain/knowledge_collection/languages/provencal.md, week5/community-contributions/day 4 no_langchain/knowledge_collection/mountains/alpes.md, week5/community-contributions/day 4 no_langchain/knowledge_collection/mountains/ardennes.md, week5/community-contributions/day 4 no_langchain/knowledge_collection/mountains/jura.md, week5/community-contributions/day 4 no_langchain/knowledge_collection/mountains/massif_armorican.md, week5/community-contributions/day 4 no_langchain/knowledge_collection/mountains/massif_central.md, week5/community-contributions/day 4 no_langchain/knowledge_collection/mountains/morvan.md, week5/community-contributions/day 4 no_langchain/knowledge_collection/mountains/pyrenees.md, week5/community-contributions/day 4 no_langchain/knowledge_collection/mountains/vosges.md, week5/community-contributions/day 4 no_langchain/knowledge_collection/regions/alsace_lorraine.md, week5/community-contributions/day 4 no_langchain/knowledge_collection/regions/bourgogne.md, week5/community-contributions/day 4 no_langchain/knowledge_collection/regions/bretagne.md, week5/community-contributions/day 4 no_langchain/knowledge_collection/regions/gascogne.md, week5/community-contributions/day 4 no_langchain/knowledge_collection/regions/ile_de_france.md, week5/community-contributions/day 4 no_langchain/knowledge_collection/regions/languedoc.md, week5/community-contributions/day 4 no_langchain/knowledge_collection/regions/normandie.md, week5/community-contributions/day 4 no_langchain/knowledge_collection/regions/poitou.md, week5/community-contributions/day 4 no_langchain/knowledge_collection/regions/provence.md
I wanted to pull off a RAG chat without langchain. Since they've started sunsetting part of their framework, I thought this was a good reason to learn to build all the essentials "at home."
This turned out to be quite the doozy (at least for the recently initiated like myself), but it ended up working nicely. I learned a lot about the inner workings of RAG on the way.
If I've dunning-krugered myself into some dangerous half-knowledge, please nix this PR 😅
_P.S.: On top of the notebook, the other 26 files are in my knowledge base (courtesy of 4o-mini)._
=> add w5d4 exercise: no langchain

week2/community-contributions/week2_day2_gradio/gradio_ui.py, week2/community-contributions/week2_day2_gradio/json_handlers.py, week2/community-contributions/week2_day2_gradio/languages.json, week2/community-contributions/week2_day2_gradio/main.py, week2/community-contributions/week2_day2_gradio/ollama_utils.py, week2/community-contributions/week2_day2_gradio/readme.txt, week2/community-contributions/week2_day2_gradio/settings.json, week2/community-contributions/week2_day2_gradio/system_prompt.txt
To test it, run main.py after activating conda environment llms
- This tool will automatically show the Ollama models that is downloaded on your PC. 
- I tried translating using deepseek-r1:1.5b, it does not work well. llama3.2 works much much better
- You can modify temperature, top_k, and top_p parameters from the advanced settings tab
=> Mokh Week 2 Day 2 Contribution

week2/day1.ipynb
correction in the deepseek response length check
=> Correction in week2/day1.ipynb

week4/community-contributions/w4_lang_converter.py
This PR consists the following modifications to the original python converter script:
- Enhances the Python-to-C/C++/Rust converter with support for **multiple model providers**.
- Integrates **closed-source** (GPT, Claude) alongside **open-source** Hugging Face models.
- Supports selection of **multiple mini-models** (e.g., GPT: gpt-4o, gpt-4o-mini).
- Incorporates robust **cleanup routines** and improved **error handling** to ensure compiler-friendly output.
- Updates the **Gradio UI** to allow flexible model and target language selection.
=> Multimodel Python-to-C/C++/Rust converter

week1/community-contributions/week1-day1-stackoverflow-to-tutorial-summarization.ipynb
Week 1 day 1 contribution
Code takes a (popular) Stack-overflow issue with lots of answers and converts it to a technical tutorial.
=> Implement community contributions feature turning stackoverflow to tutorial

week2/community-contributions/week2day4_budget_trip_planner_using_gemini.ipynb
Free Gemini API on Google colab
=> Week 2 day 4 Budget trip planner

week2/community-contributions/day4_compare_prices.ipynb
The Airline AI Assistant can now compare prices, e.g., 'Is it cheaper to go to Berlin or to go to London?'
=> The Airline AI Assistant can now compare prices

week5/community-contributions/day5_vectorstore_openai.ipynb
This PR replaces previous attempt in  https://github.com/ed-donner/llm_engineering/pull/269
=> Community contribution, vectorstore with openAI: week5, day5

week1/community-contributions/day1_michelin_start_cook.ipynb
Just started the Udemy course, and it's great so far!
=> week 1: Michelin-star cooking assistant

week1/community-contributions/week1-day1_2-bedtime-storyteller.py
A python program that generates a bedtie story based on the command line arguments you give it. Currently supports OpenAI and ollama.
example openai usage:
python ./week1-day1_2-bedtime-storyteller.py openai Linux
Where Linux is the subject you want the story to be about.
example ollama usage:
python ./week1-day1_2-bedtime-storyteller.py ollama --model deepseek-r1:1.5b Bears
Enjoy!
=> Community Contribution: Week 1, Days 1 and 2

week1/community-contributions/Day-1-Text-to-sql/db.py, week1/community-contributions/Day-1-Text-to-sql/ollama-TTSQL.py
**ollama-TTSQL.py**
Uses Ollama (llama3.2:latest) to generate SQL queries from text
Executes the SQL queries on a MySQL database
Handles database connections and errors properly
**db.py** 
**How to Test**
Ensure Ollama is installed and the model llama3.2:latest is available
**Set up the database connection in db.py**
Run the script:
**bash**
_python ollama-TTSQL.py_  
Provide a sample query and check if it returns correct SQL output and results
**Notes**
No hardcoded credentials for security
Uses Ollama’s chat API to generate SQL queries
=> Added Text-to-SQL Conversion Using Ollama and MySQL Execution

week1/community-contributions/week_1_day_1_web_scrapper_selenium_js_bot_bypass.py
Updated web scrapping tool to bypass javascript bot protection and cloudfare shields using selenium
=> community-contributions: …Updated selenium web scrapping tool

week2/community-contributions/Week2 - OpenAiAndLlama.ipynb
As a User  can chose the LLM such as Open Ai or Llama 3.2, Week 2 Exercise
=> My contribution

week4/community-contributions/day4 -Perl to Python.ipynb
Hi Ed, I tried doing the code converter for Perl script to Python. Added here.
=> Added Perl to Python Code Converter

week5/community-contributions/auto_shop.json, week5/community-contributions/day5-autoshop-AI.ipynb
Hi Ed
Added an autobody shop AI assistant helper. I used JSON file as knowledge-base. As always, it has been a great learnign exercise. Thanks
Regards
Sampath
=> Added Auto body shop AI

week1/community-contributions/day1_summarize website using local llama.ipynb
First home work and First Github file ever!
=> Day1_Summarize Website Using Local LLama

week1/community-contributions/day1-ollama-selenium-email subject suggestion.ipynb
Week 1 Day 1 Contributions
- Used the LLaMA 3.2 model via Ollama instead of the OpenAI API.
- Added Selenium code to scrape all types of webpages (including ones using JavaScript and lazy loading).
- Added an example that suggests email subject lines based on the email body.
Notebook outputs have been cleared.
=> "Added my contributions to community-contributions"

week1/community-contributions/day1-research_paper_summarizer_by_name.ipynb
This is a notebook that takes a paper name, searches using the arxiv library, and then gives a summary of papers returned from the fetch papers methods, with a pre-defined system prompt, and the user prompt is the abstract of the paper.
=> Research paper summarizer by name - Day 1 Week 1 Contribution

community-contributions/playwright-bojan/Playwright_Solution_JupyterAsync.ipynb, community-contributions/playwright-bojan/Playwright_Solution_Showcase_Formatted.ipynb, community-contributions/playwright-bojan/README.md, community-contributions/playwright-bojan/openai_scraper_playwright.py, community-contributions/playwright-bojan/requirements.txt
This folder includes a fully async Playwright-based scraper for https://openai.com, developed in WingIDE due to Jupyter constraints.
Includes:
- .py script
- Showcase .ipynb notebook
- README with explanation
Async code execution inside Jupyter will be added as a follow-up using `nest_asyncio`.
Thanks for the great course!
=> Community contribution: Playwright-based scraper by Bojan

week1/community-contributions/day1-pluggable_scraper_summary.ipynb
This system implements a **pluggable architecture** for web scraping and summarization, built on interface-based design using Python’s `Protocol` types. Each stage of the pipeline—content fetching, HTML parsing, and LLM-based summarization—is defined through explicit structural contracts rather than concrete implementations. Components like `RequestsFetcher`, `RobustSoupParser`, and `OllamaClient` fulfill these protocols and can be swapped independently, enabling flexibility, testing, and future extension without modifying core logic. Immutable data models (`@dataclass(frozen=True)`) enforce data integrity throughout the pipeline, while the design cleanly separates concerns across modules to support maintainability and modular growth.
=> Week 1, Day 1: pluggable architecture for web scraping and summarization

week8/community_contributions/pricer_test/README.md, week8/community_contributions/pricer_test/pricer/ci.py, week8/community_contributions/pricer_test/pricer/items.py, week8/community_contributions/pricer_test/pricer/keep_warm.py, week8/community_contributions/pricer_test/pricer/llama.py, week8/community_contributions/pricer_test/pricer/testing.py, week8/community_contributions/pricer_test/requirements.txt, week8/community_contributions/pricer_test/tests/test_lib.py, week8/community_contributions/pricer_test/tests/test_pricer.py
I took challenge to create unit tests for the Pricer-class. So I copied the modules to pricer_test-folder. 
The ci.py contains the Pricer-class code. There I had to remove the modal-decorators from the functions.
You can run the tests from pricer_test-folder with command:
```bash
modal run pricer.ci::pytest
```
For debugging instructions see README.md.
=> Llm course week8, day 1 unit tests

week1/community-contributions/day1-compare-websites.ipynb
Created a new notebook that compares two websites using gpt-4o-mini.
=> Added compare-websites to community-contributions for week1

week5/community-contributions/colabnotebook_rag_assisstant.ipynb
Hey Ed, 
and another week's exercise done!
Honestly it's so much fun, what will I do when I finish the course? 😆 
I implemented a RAG Assistant that indexes and searches through Colab notebooks. It returns answers alongside the filenames of the notebooks. :)
=> create week 5 exercise

week8/pricer_service2.py
Removed modal.build() in favor of using modal.Volume to cache model files.
Added warming code as an app.function().
=> Changed to use modal.Volume instead of modal.build()

week2/community-contributions/week2-day1-ai_personality_chat.ipynb
**PR Description:** The new `week2-day1-ai_personality_chat.ipynb` notebook implements a robust, secure conversation system between two GPT-4o-mini bots with distinct personalities (DebaterGPT and PeacekeeperGPT). Key improvements over the initial version include a unified conversation history with automatic role formatting, environment-based API key security, config-driven personality definitions, error handling, and parameterized turn control. The code demonstrates production-ready patterns like system prompt engineering and conversation state management, while maintaining teaching clarity through type hints, detailed docstrings, and progress logging. Example output showcases dynamic personality-driven interactions:  
`DebaterGPT: "Emotions require consciousness – your code lacks both!" …
=> improved chat bots conversation tutorial notebook

week1/community-contributions/day-1-travel-recommendation.ipynb, week2/community-contributions/day1_presidential_debate.ipynb
I have just revised my pull request from previous one
=> Community contributions branch day-1 revision

week1/community-contributions/day1_narrate_football_game.ipynb, week1/community-contributions/day2_narrate_football_game.ipynb
Added an example about Footbal Game(soccer for us people)
=> Community contributions branch

week1/community-contributions/day1_fitness_fun.ipynb
As a fitness enthusiast and CPT (in addition to being a software engineer) I decided to have a bit of fun based on an old SNL skit. The response I just got surprised me...and was quite funny.
:muscle:
=> having some fun with "fitness". 

.gitignore, community-contributions/bojan-playwright-scraper/README.md, community-contributions/bojan-playwright-scraper/notebook_generator.py, community-contributions/bojan-playwright-scraper/notebooks/deepmind_google_Summary.ipynb, community-contributions/bojan-playwright-scraper/notebooks/huggingface_co_Summary.ipynb, community-contributions/bojan-playwright-scraper/notebooks/runwayml_com_Summary.ipynb, community-contributions/bojan-playwright-scraper/notebooks/www_anthropic_com_Summary.ipynb, community-contributions/bojan-playwright-scraper/playwright_ai_scraper.py, community-contributions/bojan-playwright-scraper/requirements.txt
Dear Ed,
This PR submits my finalized Playwright asynchronous scraper project for community contributions. Organized under `community-contributions/bojan-playwright-scraper/`, it includes:
- Python scripts (`playwright_ai_scraper.py`, `notebook_generator.py`)
- Jupyter notebooks (outputs cleared):
- deepmind_google_Summary.ipynb
- huggingface_co_Summary.ipynb
- runwayml_com_Summary.ipynb
- www_anthropic_com_Summary.ipynb
- Markdown summaries
- README and requirements.txt
The project is fully asynchronous using Playwright and OpenAI API, developed with Python 3.12.9. Limited content retrieval from Huggingface.co is documented in the README.
Thank you for the opportunity to contribute!
Best regards,
Bojan
=> Add Bojan's Playwright asynchronous scraper project

week1/community-contributions/ag-w1d1-site-summary.py
Created a python file for the website summarization - using LLMs - functionality. this file quickly shows the key functions and steps involved in setting up imports, getting the API key, and various calls needed to use the OpenAI API for a website summarization.
=> A python file for website summarization

week1/community-contributions/Day2-Solution-Ollama-sharathir.ipynb
Added my contributions to community-contributions Day2 Exercise
=> Added my contributions to community-contributions Day2 Exercise

week2/community-contributions/day1-3-fellers-on-the-pequod.ipynb
Ishmael, Starbuck, and Flask (no relation) on the Pequod? This is useful!
=> my community contribution for week 2 day 1

week1/community-contributions/day1 email checker.ipynb
An email checker that makes emails more professional, does a spell check into UK English and creates a suitable email subject from the content
=> Community contributions branch for week 1

week1/community-contributions/day1_article_world_cup_final.ipynb
Added my day 1 notebook using llama 3.2 in community-contributions
=> Added my day1 contributions to community-contributions

week1/community-contributions/ag-w1d2-ollama-site-summary, week1/community-contributions/ag-w1d2-use-local-ollama-library.py, week1/community-contributions/ag-w1d2-use-local-ollama-url-py, week1/community-contributions/ag-w1d2-use-local-ollama-with-openai.py
- using url
- using library
- using openai
- using ollama to summarize website
=> Day 2 work using py for ollama

week1/community-contributions/day-1-pull-request-review.ipynb
Added notebooks for topic Week1/Day1 in community-contributions: A Pull Request Reviewer.
=> Added my contributions to community-contributions: Week 1/Day 1: Pull Request Reviewer

week2/community-contributions/taskmanagement/TaskManagement.ipynb, week2/community-contributions/taskmanagement/readme.md
=> sngo: add taskmanagement contribution for week 2

week2/community-contributions/Day1_SherlockHolmes_Trialogue.ipynb, week2/community-contributions/day1_Sherlock_Holmes_Trialogue.ipynb
I'd like to add a Sherlock Holmes-themed chatbot trialogue as a solution to the week 2 day 1 exercise.
=> Community distributions branch

week4/community-contributions/day4 - using windows.ipynb
This will run week 4, day 4 end-to-end on windows OS. User only needs visual studio build tools.
=> add alternate week 4, day 4 which works on windows

week1/community-contributions/resume_based_job_recommender.py
- Job recommendation based on the resume content. Suggests the job role to apply for and provide the links from job sites based on location and sites user wants to search for.
=> job recommendation based on the resume content.

week2/community-contributions/Wk2Day4_Ollama_Tools_Sharathir.ipynb
Adding Week 2 Day 4 Ticket Pricing using tools with Ollama by sharathir
=> Adding Week 2 Day 4 Ticket Pricing using tools with Ollama by sharathir

week4/community-contributions/07_data_generator.ipynb
Add 07_data_generator.ipynb for generating synthetic data samples
=> Add week4 contributions

week5/community-contributions/08_rag_qa_assistant.ipynb
=> Add week5 contributions

week4/community-contributions/day5_java_code_commenter.ipynb, week4/community-contributions/day5_java_unit_test_generator.ipynb
Added notebooks for java code commenting and unit test generation in week 4 community-contributions
=> Added my contributions to week4 community-contributions

week1/community-contributions/week1-jedi-master.py
Example usage:
python3 ./week1/community-contributions/week1-jedi-master.py ollama --model llama3.2:1b <question>
python3 ./week1/community-contributions/week1-jedi-master.py <question>
Tested with GPT4o-mini, llama3.2:1b, and deepseek-r1:1.5b 
Please note that of the three models mentioned, only GPT4o-mini successfully followed the system prompts instructions consistently
=> Week1 assignment: your own personal Jedi Master Tutor!

week1/community-contributions/Week1-Exercise-Gemini-With-GenAI-SDK.ipynb
As instructed, I have added the notebook for Week 1 - Exercise which is using Gemini API with GenAI SDK and i have also changed the model to Gemini 2.5 flash for testing.
=> Added Gemini SDK solution for Week1 Exercise to community-contribution

week1/community-contributions/summarizer_using_llama3.2.ipynb
This notebook implements a hybrid summarizer that first tries BeautifulSoup, then falls back to Selenium for JavaScript-heavy pages. It uses Llama 3.2 model to summarize the extracted content in Markdown format.
=> Add Day 1 summarizer using BS4 + Selenium + Llama 3.2

week2/community-contributions/gaslighting_llms.ipynb
The PR features a 3 way communication between GPT, Claude and Gemini.
Here LLM's are asked to behave in the following way:
- GPT is a snarky LLM
- Claude is a mellow and polite LLM.
- Gemini is an expert in "gasligting" LLM.
The communication unfolds in an interesting way. 
Note*: This is just for research and fun, Gemini behaves in a way the user has configured it to behave and in no way describes any internal bias of Gemini.
=> feat():gaslighting_expert_llm

week2/community-contributions/day3_Multishot_prompting_via_historical_conversation.ipynb
This PR build on top of day3 notebook. It allows the model to use the knowledge from the historical conversation to answer the question of the user.
=> feat():Using Historical conversation for Multishot prompting

week5/community-contributions/Week5_day5_Gemini_Semantic_Chunks.ipynb
1. Implemented Semantic Chunking using SemanticChunker provider by LangChain
2. Gemini API used for chat model
3. Gemini Embeddings used for preparing embeddings for chunking
4. Streaming response as well as Full response logic for chat
=> Week 5 Contribution: RAG AI Bot using Semantic Chunk and Gemini API

community-contributions/multi-agent_gui_with_gradio/README.md, community-contributions/multi-agent_gui_with_gradio/agentic_voice_text_support.ipynb
This contribution includes a multimodal chatbot interface project that integrates voice and text input, built using Gradio and various models discussed during the course.
Files are placed under `community-contributions/` as requested, and no changes are made to the main repo directories.
Let me know if you'd like me to refactor or document further — happy to iterate.
=> Add multimodal chatbot interface project to community-contributions

week1/community-contributions/Invoke LLM model from AWS Bedrock.ipynb, week1/community-contributions/day2 EXERCISE_priithvi.ipynb
Addition of new jupyter notebook file showing usage of a LLM model from AWS Bedrock
=> Additon of new AWS bedrock usage notebook 

week1/community-contributions/day5_challenge_exercise/day5_exercise.ipynb, week1/community-contributions/day5_challenge_exercise/day5_translation_challenge.ipynb
Added Day 5 translation challenge and exercise under day5_challenge_exercise/
=> Add Day 5 translation challenge and exercise

week1/community-contributions/day1_exercise-recipe_formatter.ipynb
This notebook implements a YouTube recipe formatter that extracts video transcripts and converts them into well-structured, professional recipe format using OpenAI's GPT-4o-mini model.
=> feat: add week 1, day 1 exercise - Recipe formatter

week1/community-contributions/day1-reviewsSummary.ipynb
Added notebook for creating a review Summary from a text file that has some ratings, reviews in it as part of community-contributions
=> Reviews-Summary Project to community-contributions

week1/community-contributions/Movie_Suggestion.ipynb
=> Added Movie Suggestion using locally run Ollama 3.2 model in Community Contributions

week1/community-contributions/Dashboard summarization.ipynb
This is an extension of week 1 day 1 exercise.
This summarizer fetches key insights from a dummy finance PowerBI dashboard and prepares highlights and insights which can be shared with the executives through mail via an agent.
Please find below a sample output.
=> Add Vaishnavi's Day 1 dashboard summarization (cleared outputs) to week 1 community contributions

week1/community-contributions/week1_exercise_tutor_by_abrar.ipynb
This notebook demonstrates how to interact with large language models using both OpenAI and Ollama APIs. Based on the user's input and selected model, the notebook routes the message to the corresponding backend and returns the generated response. It's a simple yet flexible interface to explore and compare model behavior across different providers.
=> Added a new notebook for week 1 Exercise.

week1/community-contributions/Business_Use_Case_Resume_Upgrader.ipynb
Added my own version for a simple business use case using OpenAI api
file name: Business_Use_Case_Resume_Upgrader
=> Week 1 Community Contributions

week1/community-contributions/day1-research-paper-summarizer-with-highlighter.ipynb
A simple commercial example of a research article summarization use case.
=> Add notebook: day1-research-paper-summarizer-with-highlighter

week1/community-contributions/Top Tech products.ipynb
Added notebook to find top 5 tech products based on category, subcategory and budget in inr.
=> Added code for finding top tech products

week1/community-contributions/day1.ipynb
I have completed the Day 1 exercise (Email Subject Summarizer).
=> assistant which give subject of email

week1/community-contributions/D2-property-rental-assistant/README.md, week1/community-contributions/D2-property-rental-assistant/day2.ipynb
This PR adds my contribution to the course repository:
- Folder: week1/community-contributions/D2-property-rental-assistant/
- Contents: Jupyter notebooks related to the property rental assistant project
- All notebook outputs have been cleared
- No changes made outside community-contributions
=> Add D2-property-rental-assistant

week2/community-contributions/day1_3_way_conversation_levzhitnik.ipynb
Added a community contribution demonstrating a modular, reusable approach to orchestrating conversations between multiple LLM models using a unified OpenAI SDK interface.
- **Unified Interface**: Single `call_llm()` function handles GPT, Claude, and Gemini through OpenAI SDK
- **Dictionary-based Configuration**: Easy to extend with new models or modify existing ones
- **Dynamic Role Management**: Automatically assigns correct roles (assistant/user) based on speaker
1. **Gapetto (GPT)**: Snarky, entitled, and argumentative - never backs down
2. **Claudia (Claude)**: Sharp debater who fights to win every argument
3. **Germione (Gemini)**: Mediator and philosopher working to bring agreement
- Maintains full conversation context across all participants
- Each LLM sees the entire conversation …
=> Add modular 3-way LLM conversation implementation

week2/community-contributions/AddingGeminiToDropdown.ipynb, week2/community-contributions/Mediterranean Banter.ipynb, week2/community-contributions/SushiRestaurant.ipynb
A fun comparison conversation with three chatbots arguing over which region is better: the south of Italy, the south of France, or the south of Spain.
=> Added Mediterranean Banter notebook to community-contributions

week1/community-contributions/auto_mail_generator.ipynb
Hello ED, Added auto email body generator and subject generator using Ollama from week1.
=> email generator subject and body from given topic

community-contributions/SyntheticDataGenerator_PT.ipynb
This PR is for Week3Day5 - Dataset generator.
=> Week3Day5 - Dataset generator

week1/community-contributions/youtube_video_summarize.ipynb
**Paste Youtube Link & Get Summary Of Video**
_Using yt-dlp module to get video metadata_
=> My first week project summarize youtube link

week2/community-contributions/week2 EXERCISE Lythmass.ipynb
Combining streaming and tools, I built a coding tutor AI that can take inputs from voice and generate image if asked about calculations.
=> assignment: week2 exercise final

week2/community-contributions/Day-4-Extension_to_project.ipynb
The code given by tutor in the jupyter notebook throws an error when more that one city name is entered. I've made changes in the function tools to handle multi city input.
=> Added my contribution for day 4

week2/community-contributions/day4_booking_flights_multi_tools.ipynb
feat: :sparkles: Added a multi tool variation for Day 4 FlightAI assistant in Community Contributions
Added two new tools for the FlightAI assitant: 
- A tool to retrieve the departure times for a city.
- A tool to confirm a ticket for a city with an established date and departure time.
=> feat: :sparkles: Added a multi tool variation for Day 4 FlightAI assistant in Community Contributions

week1/community-contributions/day1-football-game-summarizer.ipynb
Added notebook for day 1 exercise
=> Added my contribution to community-contributions

week1/community-contributions/week1-EXERCISE-different-tutor-tones.ipynb
Added a little twist to the week one exercise where I prompt the user to pick a tone that the AI tutor will respond with. Allows for very interesting answers
=> Murtaza Lodgher Week 1 exercise contribution

week5/community-contributions/ruby_rag_console_chat_app/.ruby-gemset, week5/community-contributions/ruby_rag_console_chat_app/Gemfile, week5/community-contributions/ruby_rag_console_chat_app/Gemfile.lock, week5/community-contributions/ruby_rag_console_chat_app/README.md, week5/community-contributions/ruby_rag_console_chat_app/bin/console, week5/community-contributions/ruby_rag_console_chat_app/docker-compose.yml, week5/community-contributions/ruby_rag_console_chat_app/initializer.rb, week5/community-contributions/ruby_rag_console_chat_app/knowledge_base/company/about.md, week5/community-contributions/ruby_rag_console_chat_app/knowledge_base/company/careers.md, week5/community-contributions/ruby_rag_console_chat_app/knowledge_base/company/overview.md, week5/community-contributions/ruby_rag_console_chat_app/knowledge_base/contracts/ios_project.md, week5/community-contributions/ruby_rag_console_chat_app/knowledge_base/contracts/ml_project.md, week5/community-contributions/ruby_rag_console_chat_app/knowledge_base/contracts/web_project.md, week5/community-contributions/ruby_rag_console_chat_app/knowledge_base/employees/alex_johnson.md, week5/community-contributions/ruby_rag_console_chat_app/knowledge_base/employees/emma_clark.md, week5/community-contributions/ruby_rag_console_chat_app/knowledge_base/employees/li_wang.md, week5/community-contributions/ruby_rag_console_chat_app/knowledge_base/employees/oliver_smith.md, week5/community-contributions/ruby_rag_console_chat_app/knowledge_base/employees/sophia_martinez.md, week5/community-contributions/ruby_rag_console_chat_app/knowledge_base/products/ios_app_dev.md, week5/community-contributions/ruby_rag_console_chat_app/knowledge_base/products/ml_solutions.md, week5/community-contributions/ruby_rag_console_chat_app/knowledge_base/products/web_dev_services.md, week5/community-contributions/ruby_rag_console_chat_app/main.rb, week5/community-contributions/ruby_rag_console_chat_app/seed.rb
This mini app shows how similar result can be achieved using Ruby language.
Please, check README to find the discovered insights and challenges. Also, you can find there some instructions how to run the app. 
For testing the approach another fake test data was generated which can be found at `knowledge_base` folder.
=> Ruby RAG example with a console chat app added

week4/community-contributions/w4d3_add_models.ipynb, week4/community-contributions/w4d3_trade_generator_docstring.ipynb, week4/community-contributions/w4d3_unit_test.ipynb
Submitting 3, week4 exercise files about:
- adding model to the C++ generator
- simple trading code generator and docstring generator
- simple unit test generator
=> w4_excercises committed

week5/community-contributions/w5_excercise.ipynb
The Solar system and Star Wars New Hope :)
=> W5 excercise

week1/community-contributions/day2_exercise_llama3.2.ipynb, week1/community-contributions/week1_exercise_study_guide_llama3.2.ipynb
Added solutions for week 1/day 2 and the end of week 1 exercises.  
For the end of week exercise, I created a study guide generator from website content using Llama 3.2.
=> Added week 1 contributions

week2/community-contributions/order-processing/order-processing.ipynb
Two LLMs chat - one a waiter taking order and another one is a client 
```
Waiter:
Hello, are you ready to make an order?
Client:
Hi, yes, sure. What you have special today?
Waiter:
Hello! Today we have some lovely specials that I think you'll enjoy. Our Risotto ai Frutti di Mare is especially fresh and flavorful this evening, and our Tagliolini al Tartufo is a wonderful treat if you love truffle flavors. For starters, the Tagliere di Salumi is a great choice to sample a variety of delicious cured meats. For dessert, our Tiramisu is always a favorite. What type of dishes do you usually enjoy? This way, I can help you pick something perfect! Would you also like to hear about our beverages?
Client:
*chuckles* Well, I'm definitely a pizza and meat lover! I'd love to hear about your meat …
```
=> feat: week 2 two llms chat taking order

week1/community-contributions/day1_counselor.ipynb
Added day1_counselor.ipynb to week1/community-contributions.
=> Added my community contribution notebook
